site_name: Aegir Coop
repo_url: https://github.com/AegirCoop/aegir-coop-docs
theme: readthedocs
site_favicon: '_images/favicon.ico'
docs_dir: .
site_dir: '/tmp/aegir-coop-docs/_site'
extra_css:
  - '_css/icons.css'
  - '_css/images.css'
  - '_css/menu.css'
  - '_css/policy.css'
  - '_css/style.css'
  - '_css/toc.css'
extra_javascript:
  - '_js/policy.js'
markdown_extensions:
  - 'attr_list'
pages:
- 'Home': 'index.md'
- 'By-laws': 'by-laws.md'
- 'By-laws':
  - 'By-law 1: Governance': 'by-laws/by-law1.md'
  - 'By-law 2: Rules of Borrowing and Warranties of Award': 'by-laws/by-law2.md'
  - 'By-law 3: Rules on Mediation of Disputes': 'by-laws/by-law3.md'
  - 'By-law 4: Rules on Valuation Reserve ': 'by-laws/by-law4.md'
  - 'Templates': 'by-laws/templates.md'
  - 'Templates':
    - 'Board Resolution on Admission as an Auxiliary Member': 'by-laws/templates/admission1.md'
    - 'Board Resolution on Admission as a Producer Member': 'by-laws/templates/admission2.md'
    - 'Board Resolution on Changes to Qualifying Shares': 'by-laws/templates/changes.md'
    - 'Stock Qualifying Shares': 'by-laws/templates/shares.md'
    - 'Application for Admission as an Auxiliary Member': 'by-laws/templates/application1.md'
    - 'Application for Admission as a Member': 'by-laws/templates/application2.md'
    - 'Member Agreement': 'by-laws/templates/agreement.md'
  - 'Commentary on Cooperative By-laws': 'by-laws/commentary.md'
  - 'Commentary on Cooperative By-laws':
    - 'Comments on By-law 1': 'by-laws/commentary/by-law1.md'
    - 'Comments on By-law 2': 'by-laws/commentary/by-law2.md'
    - 'Comments on By-law 3': 'by-laws/commentary/by-law3.md'
    - 'Comments on By-law 4': 'by-laws/commentary/by-law4.md'
- 'Policies': 'policies.md'
- 'Policies':
  - 'Terms of Service': 'policies/terms-of-service.md'
  - 'Privacy Policy': 'policies/privacy-policy.md'
  - 'Acceptable Use Policy': 'policies/acceptable-use-policy.md'
- 'Standard Contracts': 'contracts.md'
- 'Standard Contracts':
    - 'Independent Contractor Agreement': 'contracts/contractor.md'
    - 'Non-Disclosure Agreement (NDA)': 'contracts/non-disclosure.md'
- 'Procedures': 'procedures.md'
- 'Procedures':
  - 'Signing Resolutions': 'procedures/signing.md'
